import Groq from 'groq-sdk'
import type { BodyMeasurements, DragResults, GlbMeasurements } from './types'

const client = new Groq({
  apiKey: import.meta.env.VITE_GROQ_API_KEY,
  dangerouslyAllowBrowser: true,
})

// Reference values for a "typical" adult at average fitness.
// Used to contextualise the subject's measurements in the prompt.
const REF_FRONTAL_AREA  = 0.60   // m² — mid-range for standing adult
const REF_CD            = 0.80   // standard bluff-body Cd for upright human
const REF_DEPTH_WIDTH   = 0.50   // dimensionless — healthy depth:width ratio

export async function getRecommendations(
  m: BodyMeasurements,
  d: DragResults,
  glb?: GlbMeasurements | null,
): Promise<string> {

  // Contextual comparisons computed here so the model reasons from real numbers
  const areaVsRef  = ((d.frontalArea - REF_FRONTAL_AREA) / REF_FRONTAL_AREA * 100).toFixed(1)
  const cdVsRef    = ((d.Cd - REF_CD) / REF_CD * 100).toFixed(1)
  const areaSource = glb ? '3D photogrammetric reconstruction' : '2D landmark estimation'

  const glbSection = glb ? `
3D GEOMETRY (from photogrammetric model — more accurate than photo estimate):
  Body width (shoulder-to-shoulder): ${glb.realWidth.toFixed(3)} m
  Body depth (front-to-back):        ${glb.realDepth.toFixed(3)} m
  Depth-to-width ratio:              ${glb.depthToWidthRatio.toFixed(3)} (reference: ${REF_DEPTH_WIDTH})
  Frontal area (3D-derived):         ${glb.frontalArea.toFixed(4)} m²
  Streamlining deficit: ${glb.depthToWidthRatio < REF_DEPTH_WIDTH
    ? `body is ${((REF_DEPTH_WIDTH - glb.depthToWidthRatio) / REF_DEPTH_WIDTH * 100).toFixed(1)}% flatter than optimal depth-to-width ratio`
    : `depth-to-width ratio is within acceptable range`}` : ''

  const userMsg = `SUBJECT AERODYNAMIC PROFILE
Generated by: AeroMaxx v2.1 — Wind Tunnel Simulation System

DRAG EQUATION RESULTS (F = ½ρv²CdA):
  Air density (ρ):          1.225 kg/m³
  Walking speed (v):        1.4 m/s
  Drag coefficient (Cd):    ${d.Cd.toFixed(4)}  [${Number(cdVsRef) >= 0 ? '+' : ''}${cdVsRef}% vs. reference ${REF_CD}]
  Frontal area (A):         ${d.frontalArea.toFixed(4)} m²  [${Number(areaVsRef) >= 0 ? '+' : ''}${areaVsRef}% vs. reference ${REF_FRONTAL_AREA}] — source: ${areaSource}
  Instantaneous drag force: ${d.dragForce.toFixed(3)} N
  Drag power at v=1.4 m/s:  ${(d.dragForce * 1.4).toFixed(3)} W

POSTURAL ANALYSIS:
  Hunch score:              ${m.hunchScore.toFixed(3)} (0 = fully erect, 1 = severe kyphosis)
  Postural Cd penalty:      +${d.posturalPenalty.toFixed(4)}
  Shoulder-to-hip ratio:    ${m.shoulderToHipRatio.toFixed(3)}
${glbSection}
LIFETIME ENERGY IMPACT (4 hrs/day ambulation, 75-year lifespan):
  Total drag work:          ${d.lifetimeEnergy.toLocaleString('en-US', { maximumFractionDigits: 0 })} J
  Equivalent caloric cost:  ${d.calories.toFixed(0)} kcal
  Big Mac equivalents:      ${d.bigMacs.toFixed(1)}
  Days of metabolic output: ${d.daysLost.toFixed(1)}

DRAG BUDGET DECOMPOSITION:
  Frontal area contribution: ${(d.frontalArea / REF_FRONTAL_AREA * 100 - 100).toFixed(1)}% above reference baseline
  Postural Cd contribution:  ${(d.posturalPenalty / d.Cd * 100).toFixed(1)}% of total Cd
  Primary driver: ${d.frontalArea > REF_FRONTAL_AREA * 1.05 ? 'FRONTAL AREA (reduce body mass or improve posture)' : d.posturalPenalty > 0.04 ? 'POSTURAL CD PENALTY (address kyphosis and alignment)' : 'within normal parameters — marginal optimisation only'}`

  const response = await client.chat.completions.create({
    model: 'gemma2-9b-it',
    messages: [
      {
        role: 'system',
        content: `You are a biomechanical aerodynamics analyst. You have received a quantified aerodynamic profile for a human subject generated from wind tunnel simulation.

THE PHYSICS:
The drag equation F = ½ρv²CdA governs all results. Drag reduction comes from two independent levers:

1. FRONTAL AREA (A) — the dominant variable.
   Reducing A by 10% reduces drag by exactly 10%.
   Physical levers: body composition (fat mass reduction shrinks projected width),
   posture correction (forward head posture adds 3–6% to effective A).

2. DRAG COEFFICIENT (Cd) — shape and posture factor.
   Levers with documented magnitudes:
   - Thoracic kyphosis correction: 3–8% Cd reduction (restores attached flow over upper torso)
   - Shoulder retraction and depression: 2–5% Cd reduction (reduces separated flow at shoulders)
   - Core stabilisation for walking gait: 3–6% Cd improvement (reduces lateral sway, which time-averages drag upward)
   - Clothing: fitted vs. loose garments account for 5–15% Cd difference
   - Depth-to-width ratio: bodies with ratio 0.45–0.55 have 5–10% lower Cd than very flat or disproportionately thick profiles

YOUR TASK:
Write a DRAG REDUCTION PROTOCOL — exactly 4 numbered interventions ranked by expected drag reduction for THIS subject.

For each intervention:
Line 1: Name and mechanism (one sentence explaining HOW it reduces F = ½ρv²CdA for this person)
Line 2: Quantified target — state the specific number to improve (e.g. "reduce frontal area from 0.65 to ~0.60 m²" or "reduce Cd from 0.87 to ~0.82")
Line 3: Weekly protocol — specific exercise(s), sets × reps, frequency per week
Line 4: Expected drag reduction — realistic range in % based on the measured values

Base all estimates on the actual subject measurements. Reference the hunch score, frontal area deviation, and Cd breakdown specifically.
Tone: clinical, precise, no hedges, no disclaimers.`,
      },
      { role: 'user', content: userMsg },
    ],
    temperature: 0.6,
    max_tokens: 900,
  })

  return response.choices[0].message.content ?? ''
}

export async function getVisionAnalysis(frontUrl: string, sideUrl: string): Promise<string> {
  const models = [
    'meta-llama/llama-4-scout-17b-16e-instruct',
    'llava-v1.5-7b',
  ]

  for (const model of models) {
    try {
      const response = await client.chat.completions.create({
        model,
        messages: [
          {
            role: 'system',
            content: `You are a wind tunnel aerodynamics scientist. You are looking at photos of a person.
Analyze visible drag factors: posture, hair, clothing fit, body composition, head position, asymmetries.
Add 2 additional recommendations beyond the biomechanical ones already given.
Reference specific visible features. Clinical tone. Realistic improvement ranges. No character breaks.`,
          },
          {
            role: 'user',
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            content: [
              { type: 'text', text: 'Analyze for aerodynamic drag factors visible in these photos. Provide 2 additional recommendations.' },
              { type: 'image_url', image_url: { url: frontUrl } },
              { type: 'image_url', image_url: { url: sideUrl } },
            ] as any,
          },
        ],
        temperature: 0.6,
        max_tokens: 600,
      })

      return response.choices[0].message.content ?? ''
    } catch (err) {
      console.warn(`[AeroMaxx] Vision model ${model} failed:`, err)
    }
  }

  throw new Error('All vision models failed')
}
